name: Node-app

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.NODE_EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.NODE_HOST_DNS }}
          REMOTE_USER: ${{ secrets.NODE_USERNAME }}
          TARGET: ${{ secrets.NODE_TARGET_DIR }}

      - name: Install PM2 for Root User
        run: sudo npm install -g pm2
          
      - name: Executing script file
        run: sh script.sh

      - name: Restart apache
        run: |
          apt install -y apache2
          systemctl restart apache2
           

     
