name: Deploy

on:
  push:
    branches: main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.NODE_EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.NODE_HOST_DNS }}
          REMOTE_USER: ${{ secrets.NODE_USERNAME }}
          TARGET: ${{ secrets.NODE_TARGET_DIR }}

      - name: SSH into EC2 and Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NODE_HOST_DNS }}  
          username: ${{ secrets.NODE_USERNAME }}  
          key: ${{ secrets.NODE_EC2_SSH_KEY}}  
          script: |
            cd /var/www/html 
            ls -ll
            pwd
            git pull https://github.com/KarthickMuppilirajan/node.git
            cat hello-world.js
            sudo npm i 
            sudo npm install -g pm2
            sudo pm2 list
            sudo pm2 restart hello-world.js